FROM python:3.11-slim

WORKDIR /app

COPY ./NLP-API/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./NLP-API /app

EXPOSE 5001

ENV TRANSFORMERS_CACHE=/app/hf-cache

CMD ["python", "updated_api.py"]
